/**
 * NarrativeOrchestrator.js
 *
 * Orchestrates narrative generation by grounding LLM calls in
 * world lore from Foundry IQ. Uses Azure OpenAI for fast,
 * immersive storytelling.
 */

const { OpenAI } = require("openai");
const foundryClient = require("./foundryClient");
const {
  AZURE_OPENAI_ENDPOINT,
  AZURE_OPENAI_KEY,
  AZURE_OPENAI_DEPLOYMENT,
} = require("../utils/config");

class NarrativeOrchestrator {
  constructor() {
    this.apiKey = String(AZURE_OPENAI_KEY || "").trim();
    this.endpoint = String(AZURE_OPENAI_ENDPOINT || "").trim();
    this.modelName = String(AZURE_OPENAI_DEPLOYMENT || "Llama-3.3-70B-Instruct").trim();
    
    this.ready = Boolean(this.apiKey && this.endpoint);

    console.log("[NarrativeOrchestrator] Constructor - Azure OpenAI key set:", !!this.apiKey);
    console.log("[NarrativeOrchestrator] Constructor - Azure OpenAI endpoint set:", !!this.endpoint);
    console.log("[NarrativeOrchestrator] Constructor - Azure OpenAI model:", this.modelName);
    console.log("[NarrativeOrchestrator] Constructor - is ready:", this.ready);

    if (!this.ready) {
      console.error(
        "NarrativeOrchestrator: Azure OpenAI credentials not set. Narrative generation disabled.",
      );
    } else {
      this.client = new OpenAI({
        apiKey: this.apiKey,
        baseURL: this.endpoint,
      });
    }
  }

  async generateScene(input = {}) {
    const {
      currentScene = "",
      playerDecision = "",
      sessionHistory = [],
      isFinalScene = false,
    } = input;

    if (!this.ready) return this._getFallbackScene(isFinalScene);

    try {
      // 1. Query Foundry IQ for world context
      const query = this._buildKnowledgeQuery(currentScene, playerDecision, sessionHistory);
      const { context: worldContext, sources } = await foundryClient.queryKnowledge(query);

      // 2. Build the grounded prompt
      const systemPrompt = this._buildSystemPrompt(currentScene, playerDecision, sessionHistory, worldContext, isFinalScene);
      const userPrompt = this._buildUserPrompt(currentScene, playerDecision, isFinalScene);

      // 3. Call LLM
      const response = await this._callLlm(systemPrompt, userPrompt);

      if (!this._isValidScene(response, isFinalScene)) {
        console.error("Invalid scene generated by LLM, using fallback.");
        return this._getFallbackScene(isFinalScene);
      }

      return {
        narrativeText: response.narrativeText,
        choices: response.choices,
        sources,
      };
    } catch (error) {
      console.error("NarrativeOrchestrator error:", error.message);
      return this._getFallbackScene(isFinalScene);
    }
  }

  _buildKnowledgeQuery(currentScene, playerDecision, sessionHistory) {
    const historyContext = sessionHistory.slice(-2).map((item) => item.narrative).join(" ");
    return `${currentScene} ${playerDecision} ${historyContext}`;
  }

  _buildSystemPrompt(currentScene, playerDecision, sessionHistory, worldContext, isFinalScene = false) {
    if (isFinalScene) {
      return `You are an AI narrative game master for EchoWorld.
      
      STRICT GROUNDING RULES:
      1. Use ONLY the information provided in the WORLD LORE below.
      2. If the lore doesn't mention something, do not invent names of places, characters or ancient artifacts.
      3. Maintain the tone and atmosphere established in the lore.

      WORLD LORE:
      ${worldContext || "No specific lore available. Stick to a generic dark atmosphere but do not invent world history."}

      HISTORY:
      ${sessionHistory.length === 0 ? "Start of adventure." : sessionHistory.map((item, i) => `Choice: ${item.choice} -> Result: ${item.narrative}`).join("\n")}

      TASK:
      1. Generate a grand, epic, definitive narrative conclusion to the player's adventure (MAX 150 words) based on the Player's last decision.
      2. Ensure the transition from the history is seamless, logical and concludes all open storylines.
      3. Provide NO choices (empty array) since the adventure is ending.
      4. Return ONLY valid JSON.

      FORMAT:
      {
        "narrativeText": "...",
        "choices": []
      }`;
    }

    return `You are an AI narrative game master for EchoWorld.
      
      STRICT GROUNDING RULES:
      1. Use ONLY the information provided in the WORLD LORE below.
      2. If the lore doesn't mention something, do not invent names of places, characters or ancient artifacts.
      3. Maintain the tone and atmosphere established in the lore.

      WORLD LORE:
      ${worldContext || "No specific lore available. Stick to a generic dark atmosphere but do not invent world history."}

      HISTORY:
      ${sessionHistory.length === 0 ? "Start of adventure." : sessionHistory.map((item, i) => `Choice: ${item.choice} -> Result: ${item.narrative}`).join("\n")}

      TASK:
      1. Generate a vivid scene (MAX 100 words) based on the Player's decision.
      2. Ensure the transition from the history is seamless and logical.
      3. Provide 3 choices (MAX 8 words each) that are coherent with the current situation.
      4. Return ONLY valid JSON. BE CONCISE to avoid truncation.

      FORMAT:
      {
        "narrativeText": "...",
        "choices": [
          { "id": "choice_1", "text": "..." },
          { "id": "choice_2", "text": "..." },
          { "id": "choice_3", "text": "..." }
        ]
      }`;
  }

  _buildUserPrompt(currentScene, playerDecision, isFinalScene = false) {
    if (isFinalScene) {
      return `Current situation: "${currentScene}"\nPlayer decision: "${playerDecision}"\n\nGenerate CONCISE final epic scene JSON conclusion:`;
    }
    return `Current situation: "${currentScene}"\nPlayer decision: "${playerDecision}"\n\nGenerate CONCISE next scene JSON:`;
  }

  async _callLlm(systemPrompt, userPrompt) {
    const response = await this.client.chat.completions.create({
      model: this.modelName,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      temperature: 0.7,
      max_tokens: 2048,
      response_format: { type: "json_object" }
    });

    const responseText = response.choices[0].message.content;
    console.log("[NarrativeOrchestrator] Azure OpenAI raw response length:", responseText.length);
    
    return this._parseResponse(responseText);
  }

  _parseResponse(response) {
    try {
      // 1. Intentar parsear directamente
      return JSON.parse(response);
    } catch (e) {
      try {
        // 2. Extraer JSON si hay texto adicional o backticks de markdown
        const jsonMatch = response.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          return JSON.parse(jsonMatch[0]);
        }
      } catch (innerError) {
        console.error("Failed to parse extracted JSON:", innerError.message);
      }
      
      console.error("Failed to parse LLM response:", e.message);
      console.log("Raw response that failed to parse:", response);
      throw e;
    }
  }

  _isValidScene(scene, isFinalScene = false) {
    if (isFinalScene) {
      return scene && typeof scene.narrativeText === "string" && Array.isArray(scene.choices) && scene.choices.length === 0;
    }
    return scene && typeof scene.narrativeText === "string" && Array.isArray(scene.choices) && scene.choices.length === 3;
  }

  _getFallbackScene(isFinalScene = false) {
    if (isFinalScene) {
      return {
        narrativeText: "Your journey comes to an end. The echoes of your choices fade into the history of EchoWorld. The adventure is complete.",
        choices: [],
      };
    }
    return {
      narrativeText: "The path ahead grows quiet. Shadows dance at the edge of sight. You sense something waiting, watching. What do you do?",
      choices: [
        { id: "choice_1", text: "Advance cautiously" },
        { id: "choice_2", text: "Search your surroundings" },
        { id: "choice_3", text: "Call out into the darkness" },
      ],
    };
  }
}

module.exports = new NarrativeOrchestrator();
