/**
 * NarrativeOrchestrator.js
 *
 * Orchestrates narrative generation by grounding LLM calls in
 * world lore from Foundry IQ. Uses Google Gemini for fast,
 * immersive storytelling.
 */

const { GoogleGenerativeAI } = require("@google/generative-ai");
const foundryClient = require("./foundryClient");
const {
  GEMINI_API_KEY,
  GEMINI_MODEL,
} = require("../utils/config");

class NarrativeOrchestrator {
  constructor() {
    this.apiKey = String(GEMINI_API_KEY || "").trim();
    this.modelName = String(GEMINI_MODEL || "gemini-3.5-flash").trim();
    
    this.ready = Boolean(this.apiKey);

    console.log("[NarrativeOrchestrator] Constructor - Gemini key set:", !!this.apiKey);
    console.log("[NarrativeOrchestrator] Constructor - Gemini model:", this.modelName);
    console.log("[NarrativeOrchestrator] Constructor - is ready:", this.ready);

    if (!this.ready) {
      console.error(
        "NarrativeOrchestrator: Gemini credentials not set. Narrative generation disabled.",
      );
    } else {
      this.genAI = new GoogleGenerativeAI(this.apiKey);
    }
  }

  async generateScene(input = {}) {
    if (!this.ready) return this._getFallbackScene();

    const {
      currentScene = "",
      playerDecision = "",
      sessionHistory = [],
    } = input;

    try {
      // 1. Query Foundry IQ for world context
      const query = this._buildKnowledgeQuery(currentScene, playerDecision, sessionHistory);
      const { context: worldContext, sources } = await foundryClient.queryKnowledge(query);

      // 2. Build the grounded prompt
      const systemPrompt = this._buildSystemPrompt(currentScene, playerDecision, sessionHistory, worldContext);
      const userPrompt = this._buildUserPrompt(currentScene, playerDecision);

      // 3. Call Gemini
      const response = await this._callGemini(systemPrompt, userPrompt);

      if (!this._isValidScene(response)) {
        console.error("Invalid scene generated by Gemini, using fallback.");
        return this._getFallbackScene();
      }

      return {
        narrativeText: response.narrativeText,
        choices: response.choices,
        sources,
      };
    } catch (error) {
      console.error("NarrativeOrchestrator error:", error.message);
      return this._getFallbackScene();
    }
  }

  _buildKnowledgeQuery(currentScene, playerDecision, sessionHistory) {
    const historyContext = sessionHistory.slice(-2).map((item) => item.narrative).join(" ");
    return `${currentScene} ${playerDecision} ${historyContext}`;
  }

  _buildSystemPrompt(currentScene, playerDecision, sessionHistory, worldContext) {
    return `You are an AI narrative game master for EchoWorld.
      
      STRICT GROUNDING RULES:
      1. Use ONLY the information provided in the WORLD LORE below.
      2. If the lore doesn't mention something, do not invent names of places, characters or ancient artifacts.
      3. Maintain the tone and atmosphere established in the lore.

      WORLD LORE:
      ${worldContext || "No specific lore available. Stick to a generic dark atmosphere but do not invent world history."}

      HISTORY:
      ${sessionHistory.length === 0 ? "Start of adventure." : sessionHistory.map((item, i) => `Choice: ${item.choice} -> Result: ${item.narrative}`).join("\n")}

      TASK:
      1. Generate a vivid scene (MAX 100 words) based on the Player's decision.
      2. Ensure the transition from the history is seamless and logical.
      3. Provide 3 choices (MAX 8 words each) that are coherent with the current situation.
      4. Return ONLY valid JSON. BE CONCISE to avoid truncation.

      FORMAT:
      {
        "narrativeText": "...",
        "choices": [
          { "id": "choice_1", "text": "..." },
          { "id": "choice_2", "text": "..." },
          { "id": "choice_3", "text": "..." }
        ]
      }`;
  }

  _buildUserPrompt(currentScene, playerDecision) {
    return `Current situation: "${currentScene}"\nPlayer decision: "${playerDecision}"\n\nGenerate CONCISE next scene JSON:`;
  }

  async _callGemini(systemPrompt, userPrompt) {
    const model = this.genAI.getGenerativeModel({ 
      model: this.modelName,
      generationConfig: { 
        responseMimeType: "application/json",
        temperature: 0.7,
        topP: 0.95,
        maxOutputTokens: 2048,
      }
    });

    const result = await model.generateContent(`${systemPrompt}\n\n${userPrompt}`);
    const responseText = result.response.text();
    console.log("[NarrativeOrchestrator] Gemini raw response length:", responseText.length);
    
    return this._parseResponse(responseText);
  }

  _parseResponse(response) {
    try {
      // 1. Intentar parsear directamente
      return JSON.parse(response);
    } catch (e) {
      try {
        // 2. Extraer JSON si hay texto adicional o backticks de markdown
        const jsonMatch = response.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          return JSON.parse(jsonMatch[0]);
        }
      } catch (innerError) {
        console.error("Failed to parse extracted JSON:", innerError.message);
      }
      
      console.error("Failed to parse LLM response:", e.message);
      console.log("Raw response that failed to parse:", response);
      throw e;
    }
  }

  _isValidScene(scene) {
    return scene && typeof scene.narrativeText === "string" && Array.isArray(scene.choices) && scene.choices.length === 3;
  }

  _getFallbackScene() {
    return {
      narrativeText: "The path ahead grows quiet. Shadows dance at the edge of sight. You sense something waiting, watching. What do you do?",
      choices: [
        { id: "choice_1", text: "Advance cautiously" },
        { id: "choice_2", text: "Search your surroundings" },
        { id: "choice_3", text: "Call out into the darkness" },
      ],
    };
  }
}

module.exports = new NarrativeOrchestrator();
